# Generated by Django 4.2.16 on 2024-10-26 09:41

import RecipesApp.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[RecipesApp.profiles.validators.validate_nickname_length])),
                ('first_name', models.CharField(max_length=30, validators=[RecipesApp.profiles.validators.validate_capital_letter])),
                ('last_name', models.CharField(max_length=30, validators=[RecipesApp.profiles.validators.validate_capital_letter])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
